### ISSUE TITLE
MatChipList not found

### ISSUE THREAD

**Issue by Pastorkid** [dillyboy/angular_material_data_grid#15]
Please am getting this error

`./node_modules/angular-material-data-grid/fesm2020/angular-material-data-grid.mjs:4058:247-263 - Error: export 'MatChipList' (imported as 
'i9$1') was not found in '@angular/material/chips' (possible exports: MAT_CHIP, MAT_CHIPS_DEFAULT_OPTIONS, MAT_CHIP_AVATAR, MAT_CHIP_LISTBOX_CONTROL_VALUE_ACCESSOR, MAT_CHIP_REMOVE, MAT_CHIP_TRAILING_ICON, MatChip, MatChipAvatar, MatChipEditInput, MatChipGrid, MatChipGridChange, MatChipInput, MatChipListbox, MatChipListboxChange, MatChipOption, MatChipRemove, MatChipRow, MatChipSelectionChange, MatChipSet, MatChipTrailingIcon, MatChipsModule)`

**Comment by dillyboy** [comment]
What is the version of Angular and Angular-material you are using?

**Comment by Pastorkid** [comment]
Angular 15 and Material 15

**Comment by dillyboy** [comment]
The grid was last used with Angular 14. Let me look at this and get back to you within 2 days.

**Comment by dillyboy** [comment]
It looks like the Angular Material team has completely rewritten the Chips Component since they have migrated to MDC-based Angular Material Components, I will implement a fix and put out a new version soon. For now this library will not work with Angular Material 15.

<img width="1421" alt="Screenshot 2022-11-26 at 11 51 46 AM" src="https://user-images.githubusercontent.com/10022720/204071498-fc6049ab-b769-4aaf-bfdb-b620002c1174.png">
[Migrating to MDC-based Components](https://material.angular.io/guide/mdc-migration)
